apiVersion: v1
kind: Service
metadata:
  name: tkstone-springboot-backend-service
spec:
  selector:
    app: tkstone-springboot-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

